/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nitsh
 */import java.awt.Font;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
public class sm extends javax.swing.JFrame {

    /**
     * Creates new form sm
     */
    public sm() {
        initComponents();this.setBounds(0,0,1320,820); t.setRowHeight(30);
        this.setLocationRelativeTo(null);
        t.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 25));
        int i=0;
        //for(int j=i;j<5;j++)
        int[] cs={200,250,250,180,180};
        for(int j:cs)
        {
        TableColumn c= t.getColumnModel().getColumn(i++);
        c.setMinWidth(j);
        c.setMaxWidth(j);
        c.setPreferredWidth(j);}
        t.setVisible(false);
        jScrollPane1.setVisible(false);
        set1.setVisible(false);
        set2.setVisible(false);
        set3.setVisible(false);
        set4.setVisible(false);
        set5.setVisible(false);
        cid.setVisible(false);
        name.setVisible(false);
        phno1.setVisible(false);
       q5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        goback = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        goback7 = new javax.swing.JButton();
        rcid = new javax.swing.JRadioButton();
        rname = new javax.swing.JRadioButton();
        rphno = new javax.swing.JRadioButton();
        next = new javax.swing.JButton();
        set5 = new javax.swing.JButton();
        set1 = new javax.swing.JLabel();
        cid = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        phno1 = new javax.swing.JTextField();
        set4 = new javax.swing.JLabel();
        set3 = new javax.swing.JLabel();
        set2 = new javax.swing.JLabel();
        setlabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t = new javax.swing.JTable();
        q5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        goback.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        goback.setText("<- GO BACK");
        goback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gobackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELECT ANY ONE OF THE ATTRIBUTES OF MATCH TO SEARCH :");

        goback7.setBackground(new java.awt.Color(189, 189, 247));
        goback7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        goback7.setForeground(new java.awt.Color(102, 0, 102));
        goback7.setText("HOME");
        goback7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goback7ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rcid);
        rcid.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        rcid.setText("MATCH ID");
        rcid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcidActionPerformed(evt);
            }
        });

        buttonGroup1.add(rname);
        rname.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        rname.setText("MATCH LOC");

        buttonGroup1.add(rphno);
        rphno.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        rphno.setText("MATCH DATE");
        rphno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rphnoActionPerformed(evt);
            }
        });

        next.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        next.setText("NEXT");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        set5.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        set5.setText("SEARCH");
        set5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set5ActionPerformed(evt);
            }
        });

        set1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        set1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        set1.setText("ENTER THE MATCH DETAILS :");

        cid.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N

        name.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N

        phno1.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        phno1.setText("dd-mmm-yy");

        set4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        set4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        set4.setText(" MATCH DATE :");

        set3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        set3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        set3.setText("MATCH LOC :");

        set2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        set2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        set2.setText("MATCH ID :");

        setlabel.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        setlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        t.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        t.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MATCH  ID", "MATCH LOC", "MATCH DATE", "TEAM 1 ID", "TEAM 2 ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        t.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(t);
        t.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (t.getColumnModel().getColumnCount() > 0) {
            t.getColumnModel().getColumn(0).setResizable(false);
            t.getColumnModel().getColumn(1).setResizable(false);
            t.getColumnModel().getColumn(2).setResizable(false);
            t.getColumnModel().getColumn(4).setResizable(false);
        }

        q5.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        q5.setText("SELECT AGAIN");
        q5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(goback)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 903, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(goback7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(setlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rcid)
                        .addGap(41, 41, 41)
                        .addComponent(rname)
                        .addGap(33, 33, 33)
                        .addComponent(rphno)
                        .addGap(103, 103, 103)
                        .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(236, 236, 236))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(set3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(set2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cid, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(set4, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(phno1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(set1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addComponent(set5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(304, 304, 304))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(q5, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(524, 524, 524))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(130, 130, 130)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(130, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(goback, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(goback7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rphno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rname)
                        .addComponent(rcid, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(setlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(set1)
                    .addComponent(set5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(set2))
                    .addComponent(cid, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(set3))
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phno1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(set4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                .addComponent(q5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(438, 438, 438)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(127, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gobackActionPerformed
        // TODO add your handling code here:
        try{
            Connection con= DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","NitishR","dbms");
            con.commit();
        }
        catch(Exception e )
        {
            System.err.println(e);
        }
       match a =new match();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_gobackActionPerformed

    private void goback7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goback7ActionPerformed
        // TODO add your handling code here:
        try{
            Connection con= DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","NitishR","dbms");
            con.commit();
        }
        catch(Exception e )
        {
            System.err.println(e);
        }
        aftrlogin a =new aftrlogin();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_goback7ActionPerformed

    private void rcidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcidActionPerformed
        // TODO add your handling code here:
        int i=0;
    }//GEN-LAST:event_rcidActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        t.setVisible(true);
        jScrollPane1.setVisible(true);
        set1.setVisible(true);
        set5.setVisible(true);
        q5.setVisible(true);
        if(rcid.isSelected())
        {
            set2.setVisible(true); cid.setVisible(true);
        }
        if(rname.isSelected())
        {
            set3.setVisible(true);name.setVisible(true);

        }
        if(rphno.isSelected())
        {
            set4.setVisible(true);phno1.setVisible(true);
        }
    }//GEN-LAST:event_nextActionPerformed

    private void set5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set5ActionPerformed

        if(rcid.isSelected())
        {   String s=cid.getText();
            try{
                Connection con= DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","NitishR","dbms");
                Statement st= con.createStatement();
                ResultSet rs=st.executeQuery("select m.mid,m.mloc,m.mdate,t.tid from match m,play t where m.mid='"+s+"' and m.mid=t.mid");
                if(rs.next()){
                    DefaultTableModel model = (DefaultTableModel) t.getModel();
                    String r1= rs.getString(3);
                    String r=r1.substring(0,10);
                    String a,b,c,d;
                    a=rs.getString(1);
                    b=rs.getString(2);
                    c=rs.getString(4);
                    rs.next();
                    d=rs.getString(4);
                    model.insertRow(1,new Object[]{a,b,r,c,d});
                }
                else{
                    setlabel.setText("NO RECORDS FOUND");
                }
            }
            catch(Exception e)
            {
                System.err.println(e);
            }
        }
        if(rname.isSelected())
        {
            String s=name.getText();
            try{
                Connection con= DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","NitishR","dbms");
                Statement st= con.createStatement();
                ResultSet rs=st.executeQuery("select m.mid,m.mloc,m.mdate,t.tid from match m,play t where m.mloc='"+s+"' and m.mid=t.mid");
                if(rs.next()==false){
                setlabel.setText("NO RECORDS FOUND");
                }
                else{
                    do{DefaultTableModel model = (DefaultTableModel) t.getModel();
                    String r1= rs.getString(3);
                    String r=r1.substring(0,10);
                    String a,b,c,d;
                    a=rs.getString(1);
                    b=rs.getString(2);
                    c=rs.getString(4);
                    rs.next();
                    d=rs.getString(4);
                    model.insertRow(1,new Object[]{a,b,r,c,d});
                    }while(rs.next());
                }}
            catch(Exception e)
            {
                System.err.println(e);
            }

        }
        if(rphno.isSelected())
        {
            String s=phno1.getText();
            try{
                Connection con= DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","NitishR","dbms");
                Statement st= con.createStatement();
                ResultSet rs=st.executeQuery("select m.mid,m.mloc,m.mdate,t.tid from match m,play t where m.mdate='"+s+"' and m.mid=t.mid");
                if(rs.next()==false){
                setlabel.setText("NO RECORDS FOUND");
                }
                else{
                    do{DefaultTableModel model = (DefaultTableModel) t.getModel();
                    String r1= rs.getString(3);
                    String r=r1.substring(0,10);
                    String a,b,c,d;
                    a=rs.getString(1);
                    b=rs.getString(2);
                    c=rs.getString(4);
                    rs.next();
                    d=rs.getString(4);
                    model.insertRow(1,new Object[]{a,b,r,c,d});
                    }while(rs.next());
                }
            }
            catch(Exception e)
            {
                System.err.println(e);
            }
        }
    }//GEN-LAST:event_set5ActionPerformed

    private void rphnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rphnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rphnoActionPerformed

    private void q5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5ActionPerformed
        // TODO add your handling code here:
        sm a =new sm();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_q5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cid;
    private javax.swing.JButton goback;
    private javax.swing.JButton goback7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JButton next;
    private javax.swing.JTextField phno1;
    private javax.swing.JButton q5;
    private javax.swing.JRadioButton rcid;
    private javax.swing.JRadioButton rname;
    private javax.swing.JRadioButton rphno;
    private javax.swing.JLabel set1;
    private javax.swing.JLabel set2;
    private javax.swing.JLabel set3;
    private javax.swing.JLabel set4;
    private javax.swing.JButton set5;
    private javax.swing.JLabel setlabel;
    private javax.swing.JTable t;
    // End of variables declaration//GEN-END:variables
}
